### ISSUE TITLE
Problema visualizzazione gerarchie

### ISSUE THREAD

**Issue by ghost** [therealsivie/ProgettoIngeSw-2022#1]
Quando il configuratore chiede di visualizzare le gerarchie viene mostrata solo quella di default (Libri);
ho provato ad aggiungerne una ma sembra che il metodo readGerarchie della classe JsonUtil non aggiunga a gerarchiaList tutte le gerarchie che trova nella cartella. Non credo che l'errore derivi dal path.

**Comment by miche-linux** [comment]
Il problema era che avevo aggiunto un'altra categoria radice e non un figlia di Libri
